name: pocket_lab
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  fluro: "^1.3.1"
  charts_flutter: "^0.0.1+1"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_stetho: "^0.0.1"

flutter:
  uses-material-design: true
